language: python
branches:
  only:
  - blog_source
install:
- pip install -r requirements.txt
before_script:
- pelican-themes -i ./theme/elegant
script:
- make publish github
env:
  global:
  - secure: [Encrypted Travis Key Here]
