language: python
branches:
  only:
  - blog_source
install:
  - pip install -r requirements.txt
before_script:
  - pelican-themes -i ./theme/elegant
  - openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv -in travis.enc -out travis -d
  - chmod go-rwx travis
  - eval `ssh-agent -s`
  - ssh-add travis
  - git config --global user.name "Travis-CI"
  - git config --global user.email "noreply@travis-ci.org"

script:
    - rm -rf ./output
    - rm -rf ./cache
    - rm -rf ./plugins/
    - git clone https://github.com/getpelican/pelican-plugins.git
    - mv ./pelican-plugins/ ./plugins
    - make publish
    - git clone --quiet git@github.com:yboren/yboren.github.com.git > /dev/null
    - cd yboren.github.com
    - git checkout -b master
    - rsync -rv --exclude=.git ../output/* .
    - git add -f .
    - git commit -m "Travis build $TRAVIS_BUILD_NUMBER"
    - git push -f origin master
    - echo -e "Done\n"
